AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/bundle/**/*
    - node_modules/**/*
    - bin/*
Metrics/LineLength:
  Exclude:
    - config/**/*
    - db/**/*
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
